### ISSUE TITLE
Having hard time setting up waybar (Hyprland IPC)

### ISSUE THREAD

**Issue by SyedAsadK** [Endg4meZer0/Windwaker-Dotfiles#1]
i also switched to niri and loving it since last 2 weeks.. i saw your dots and they are stunning, but i'm having a hard time figuring out how can i make waybar work and workspaces.. little help soo useful

**Comment by Endg4meZer0** [comment]
Well, first of all, my waybar is built with cava support enabled, because I use the cava module. I use Arch (btw), so I have a privilege of having waybar-cava-git as an AUR package, but there should always be a way to manually build with cava support as well, you just need to search for it.
Second, a lot of niri stuff is documented at [the waybar wiki](https://github.com/Alexays/Waybar/wiki/Module:-Niri), and I believe you can figure a lot of stuff by following the other pages in the wiki as well.

If you really can't understand something from there, then write here, I'll help as much as I can. But please, describe what do you want help with next time :)

**Comment by SyedAsadK** [comment]
Thanks got it, i did not knew waybar was chill like that.. got it working pretty goood

![image](https://github.com/user-attachments/assets/949bc6e8-e829-4bce-98e7-298e7a868abc)

**Comment by SyedAsadK** [comment]
damn i didn't knew there was a waybar-cava for btw users.. 
![image](https://github.com/user-attachments/assets/47db1618-e3c6-4440-b9cd-5456b3461e78)

i was using a script like the one in the repo for cava, thanks so much
